// PLACEHOLDER — Generated by scripts/convert-shp.mjs
// Run:  npm run convert-shp
// This file will be replaced with real ADM3 polygon data from:
//   shp/tun_admbnda_adm3_ins_20221115.shp
//
// Until the conversion is run, the map falls back to the 24-governorate
// approximation already built into tunisia_geojson.ts

export const TUNISIA_ADM3_GEOJSON: {
  type: 'FeatureCollection';
  features: Array<{
    type: 'Feature';
    id: number;
    properties: {
      id: number;
      pcode: string;
      name_ar: string;
      name_fr: string;
      name_en: string;
      gov_ar: string;
      gov_fr: string;
      del_ar: string;
      del_fr: string;
    };
    geometry: any;
  }>;
} = {
  type: 'FeatureCollection',
  features: [], // empty until convert-shp is run
};
